language: julia

os:
  - linux
  - osx

julia:
  - 1.3

env:
  global:
    - PYTHON=''

notifications:
  email: true

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add("Documenter"); Pkg.add("Literate"); Pkg.add("Plots"); Pkg.develop(PackageSpec(path=pwd()))'
        - JULIA_DEBUG=all julia --project=docs/ docs/make.jl
      after_success: skip
